OwlyStuff/amazium

- css/base.css
- css/form.css
- example.html
- forms.html
* Moves the styling for the buttons to the form.css file
* Updates the Pre & code styling
* Form example page now has the loading states for buttons in them
* Font sizes changed for headings and paragrahs
> Buttons & Typography updates

- scss/_grid-percent.scss
Updates the 100% version of Amazium's grid.
> Updates the 100% fluid grid

- scss/_base.scss
- scss/_form.scss
/cc @MikeBallan @catchamonkey @shahrukhomar
> Various amendments and spelling fixes

- gulpfile.js
- package.json
Reduces file size of built css by nearly 20K.
> [Build] Adds CSS clean to the build pipeline

- scss/_grid.scss
Combines both fluid and default grids to use flexbox FTW
> [Grid] Now uses Flexbox

- scss/_form.scss
> [Radio & Checkboxes] Updates naming and styling

- scss/_grid.scss
Removes the left or right or both padding on nested grids
> [Grid] Removes padding on nested grids to fix alignment of content

- scss/_base.scss
- scss/_form.scss
0.33s cubic-bezier(0.33, 0, 0.2, 1) 0s
> [Transition Timing] Sets all timing to the same

- scss/_grid.scss
Am i missing something or are the Hide/Show classes missing ? And i think the file needs a bit of reordering because it is irritating to go from mobile to desktop and back to mobile.
> fixed .row--width-fluid + added adjustable grid count to mobile

- scss/_form.scss
Changes the margin:0; to margin-bottom:0; on a forms last child
> [Form] last-child margin updated

- scss/_form.scss
> [Form] Updates styling of the message blocks inside a form

- scss/_base.scss
Reworked Tables to be mobile first and removes the ```!important``` from the show and hide classes as its bad OK..!
> [Base] Updates to tables and the show/hide classes

- scss/_variables.scss
New class for creating responsive boxes that follow a chosen aspect ratio.
> [Aspect Ratio Boxes] 

- scss/_grid.scss
Changes css property `flex-basic` with `flex-basis`
> Fixes grid tablet override

- scss/_grid.scss
> Adds max-width override to grid-*-tablet

- .travis.yml
> Only build master branch, otherwise PRs are built twice

- README.md
> Updated site link in readme to use HTTPS

- scss/_form.scss
- scss/_variables.scss
- Updates colors to use variables
- Buttons now have more color options
- Button states are better styled
- Changes the checkboxes background color to use the info color to be the same as radios
- Forms.scss now using mainly SCSS over plain CSS
> [Forms] Updates height of inputs and converts over the using SCSS

- .travis.yml
Allow the base branch for testing to be a version branch (starts with v) or a feature branch (starts with feature)
> Allow travis to test long release branches.

- scss/_base.scss
- scss/_columns.scss
- scss/_form.scss
- scss/_grid.scss
By adding the lobotomised owl selector there is no need to keep adding margins as its handled by ```*+*```
> V5 [Margins] Adds the lobotomised owl selector to add consistent vertical rhythm to Amazium

- scss/_base.scss
- scss/_columns.scss
- scss/_form.scss
- scss/_grid.scss
> V5 [Typography] Changes font size from px to em/rem

- scss/_base.scss
- scss/_columns.scss
- scss/_form.scss
- scss/_grid.scss
Adds new styling options to have tr hover, stripes and mobile styling
> V5 [Tables] Updates how tables are styled

- scss/_form.scss
Updates the styling and adds support of clicking the label of a switch
> [Radio and Checkboxes] Updates styling and usability 

- .travis.yml
- package.json
> Fixes travis building for npm by removing branch restrictions

- scss/_form.scss
Updates placement of the switch to be in the same position as default
> [Switch placement]  Switch placement correction

- scss/_base.scss
- scss/_columns.scss
- scss/_form.scss
- scss/_grid.scss
Have removed the lobotomised owl as it causes problems if you have script tags/hidden elements in page. And to replace this ive set up targeted element to get the same margin-top.
> [Lobotomised Owl] Removes the select all in favor of targeted elements

- scss/_form.scss
> V5 [Radio & Checkboxes] Fixes alignment of the switch

- package.json
> Release for 5.0.0-3

- package.json
> Release for 5.0.0-4

- scss/_base.scss
Adds styling by way of adding table-mobile class to a table
> V5 [Tables on mobile] Fixes styling for mobile tables

- package.json
> Release for 5.0.0-5

- package.json
> Release for 5.0.0-6

- scss/_base.scss
> [Tables] Updates styling of mobile tables on a default desktop screen

- package.json
> Release for 5.0.0-7

- npm-shrinkwrap.json
- package.json
- scss/_base.scss
- scss/_buttons.scss
- scss/_form.scss
* Removes fixed heights
* Changes the padding to use em's
* Updates color refs to use the variables.sccs file
* Removes fixed height in favor of min-height so btn txt can wrap
* Removes the top offset on the icon class
* Changes the padding to use em's
* Updates styling when used with form elements
> V5 [Typography, Btn's & Forms] 
